---
- name: Render kubernetes cluster credentials
  shell: >
    cd {{ kube_cluster_assets_dir }};
    kube-aws render credentials --generate-ca
  args:
    creates: "{{ kube_cluster_assets_dir }}/credentials/admin.pem"