apiVersion: v1
kind: Service
metadata:
  namespace: elasticsearch
  name: elasticsearch-logging
  labels:
    app: elasticsearch
    role: client
spec:
  selector:
    app: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
