---
- name: Create AWS credentials directory
  file:
    name: ~/.aws
    state: directory

- name: Set sample AWS credentials file
  set_fact:
    aws_credentials: |
      [default]
      aws_access_key_id = {{ aws_access_key_id }}
      aws_secret_access_key = {{ aws_secret_access_key }}

- name: Check AWS CLI credentials file presence
  stat:
    path: ~/.aws/credentials
  register: aws_cli_credentials

- name: Get AWS CLI credentials file contents
  set_fact:
    aws_credentials_existing: "{{ lookup('file', '~/.aws/credentials') }}"
  when: aws_cli_credentials.stat.exists

- name: Compare new and existing credentials
  assert:
    that: aws_credentials.strip() == aws_credentials_existing.strip()
    msg: AWS CLI configuration file ~/.aws/credentials exists and its contents differ from the new ones. Backup or remove it
  when: aws_cli_credentials.stat.exists

- name: Create AWS CLI credentials file
  copy:
    content: "{{ aws_credentials }}"
    dest: ~/.aws/credentials
  when: not aws_cli_credentials.stat.exists
